interface GameCapabilities {
  supportsBasicSettings: boolean;
  supportsGameMode: boolean;
  supportsDifficulty: boolean;
  supportsMaxPlayers: boolean;
  supportsPassword: boolean;
  supportsPort: boolean;
  portEditable: boolean;
  supportsPublicToggle: boolean;
  supportsModAutomation: boolean;
  modType: 'workshop' | 'manual' | 'plugin' | 'none';
  supportsAdvancedConfig: boolean;
  configFiles: string[];
  gameSpecificSettings: GameSpecificSetting[];
  requiresRestartFor: string[];
}

interface GameSpecificSetting {
  id: string;
  label: string;
  type: 'toggle' | 'select' | 'number' | 'text' | 'slider';
  category: string;
  options?: { value: string; label: string }[];
  min?: number;
  max?: number;
  step?: number;
  defaultValue: any;
  description?: string;
}

const GAME_CAPABILITIES: Record<string, GameCapabilities> = {
  Minecraft: {
    supportsBasicSettings: true,
    supportsGameMode: true,
    supportsDifficulty: true,
    supportsMaxPlayers: true,
    supportsPassword: false,
    supportsPort: true,
    portEditable: true,
    supportsPublicToggle: true,
    supportsModAutomation: false,
    modType: 'manual',
    supportsAdvancedConfig: true,
    configFiles: ['server.properties'],
    requiresRestartFor: ['gamemode', 'difficulty', 'port', 'max-players', 'pvp'],
    gameSpecificSettings: [
      {
        id: 'gamemode',
        label: 'Gamemode',
        type: 'select',
        category: 'Gameplay',
        options: [
          { value: 'survival', label: 'Survival' },
          { value: 'creative', label: 'Creative' },
          { value: 'adventure', label: 'Adventure' },
          { value: 'spectator', label: 'Spectator' },
        ],
        defaultValue: 'survival',
        description: 'Default game mode for players',
      },
      {
        id: 'difficulty',
        label: 'Difficulty',
        type: 'select',
        category: 'Gameplay',
        options: [
          { value: 'peaceful', label: 'Peaceful' },
          { value: 'easy', label: 'Easy' },
          { value: 'normal', label: 'Normal' },
          { value: 'hard', label: 'Hard' },
        ],
        defaultValue: 'normal',
        description: 'Game difficulty level',
      },
      {
        id: 'view-distance',
        label: 'View Distance',
        type: 'slider',
        category: 'Performance',
        min: 3,
        max: 32,
        step: 1,
        defaultValue: 10,
        description: 'Render distance in chunks (higher = more server load)',
      },
      {
        id: 'online-mode',
        label: 'Online Mode',
        type: 'toggle',
        category: 'Security',
        defaultValue: true,
        description: 'Requires Mojang authentication',
      },
      {
        id: 'pvp',
        label: 'PvP Enabled',
        type: 'toggle',
        category: 'Gameplay',
        defaultValue: true,
        description: 'Allow player vs player combat',
      },
    ],
  },

  'Counter-Strike 2': {
    supportsBasicSettings: true,
    supportsGameMode: false,
    supportsDifficulty: false,
    supportsMaxPlayers: true,
    supportsPassword: true,
    supportsPort: true,
    portEditable: false,
    supportsPublicToggle: true,
    supportsModAutomation: true,
    modType: 'workshop',
    supportsAdvancedConfig: true,
    configFiles: ['server.cfg'],
    requiresRestartFor: ['tickrate', 'maxplayers', 'hostname'],
    gameSpecificSettings: [
      {
        id: 'tickrate',
        label: 'Tickrate',
        type: 'select',
        category: 'Performance',
        options: [
          { value: '64', label: '64 tick' },
          { value: '128', label: '128 tick' },
        ],
        defaultValue: '64',
        description: 'Server update rate (requires restart)',
      },
      {
        id: 'friendly-fire',
        label: 'Friendly Fire',
        type: 'toggle',
        category: 'Gameplay',
        defaultValue: false,
        description: 'Allow team damage',
      },
      {
        id: 'start-map',
        label: 'Start Map',
        type: 'select',
        category: 'Maps',
        options: [
          { value: 'de_dust2', label: 'Dust 2' },
          { value: 'de_mirage', label: 'Mirage' },
          { value: 'de_inferno', label: 'Inferno' },
          { value: 'de_nuke', label: 'Nuke' },
          { value: 'de_ancient', label: 'Ancient' },
        ],
        defaultValue: 'de_dust2',
        description: 'Default starting map',
      },
    ],
  },

  'Project Zomboid': {
    supportsBasicSettings: true,
    supportsGameMode: false,
    supportsDifficulty: false,
    supportsMaxPlayers: true,
    supportsPassword: true,
    supportsPort: true,
    portEditable: true,
    supportsPublicToggle: true,
    supportsModAutomation: true,
    modType: 'workshop',
    supportsAdvancedConfig: true,
    configFiles: ['servertest.ini'],
    requiresRestartFor: ['pvp', 'mods', 'maxplayers'],
    gameSpecificSettings: [
      {
        id: 'pvp',
        label: 'PvP Enabled',
        type: 'toggle',
        category: 'Gameplay',
        defaultValue: false,
        description: 'Allow player vs player combat',
      },
      {
        id: 'safehouse',
        label: 'Safehouse Enabled',
        type: 'toggle',
        category: 'Gameplay',
        defaultValue: true,
        description: 'Allow players to claim safehouses',
      },
      {
        id: 'zombie-count',
        label: 'Zombie Population',
        type: 'select',
        category: 'World',
        options: [
          { value: '1', label: 'Insane' },
          { value: '2', label: 'Very High' },
          { value: '3', label: 'High' },
          { value: '4', label: 'Normal' },
          { value: '5', label: 'Low' },
        ],
        defaultValue: '4',
        description: 'Zombie spawn density',
      },
      {
        id: 'loot-rarity',
        label: 'Loot Rarity',
        type: 'select',
        category: 'World',
        options: [
          { value: 'very-rare', label: 'Very Rare' },
          { value: 'rare', label: 'Rare' },
          { value: 'normal', label: 'Normal' },
          { value: 'abundant', label: 'Abundant' },
        ],
        defaultValue: 'normal',
        description: 'Item spawn frequency',
      },
      {
        id: 'day-length',
        label: 'Day Length (minutes)',
        type: 'number',
        category: 'World',
        min: 5,
        max: 120,
        defaultValue: 30,
        description: 'Real-time minutes per in-game day',
      },
    ],
  },

  Valheim: {
    supportsBasicSettings: true,
    supportsGameMode: false,
    supportsDifficulty: false,
    supportsMaxPlayers: true,
    supportsPassword: true,
    supportsPort: true,
    portEditable: true,
    supportsPublicToggle: true,
    supportsModAutomation: false,
    modType: 'manual',
    supportsAdvancedConfig: true,
    configFiles: ['start_server.sh'],
    requiresRestartFor: ['all'],
    gameSpecificSettings: [
      {
        id: 'world-name',
        label: 'World Name',
        type: 'text',
        category: 'World',
        defaultValue: 'Dedicated',
        description: 'Name of the world save file',
      },
      {
        id: 'crossplay',
        label: 'Crossplay',
        type: 'toggle',
        category: 'Network',
        defaultValue: false,
        description: 'Enable crossplay with consoles',
      },
    ],
  },

  Rust: {
    supportsBasicSettings: true,
    supportsGameMode: false,
    supportsDifficulty: false,
    supportsMaxPlayers: true,
    supportsPassword: false,
    supportsPort: true,
    portEditable: false,
    supportsPublicToggle: true,
    supportsModAutomation: true,
    modType: 'plugin',
    supportsAdvancedConfig: true,
    configFiles: ['server.cfg'],
    requiresRestartFor: ['seed', 'worldsize', 'maxplayers'],
    gameSpecificSettings: [
      {
        id: 'world-size',
        label: 'World Size',
        type: 'select',
        category: 'World',
        options: [
          { value: '3000', label: 'Small (3000)' },
          { value: '4000', label: 'Medium (4000)' },
          { value: '5000', label: 'Large (5000)' },
          { value: '6000', label: 'Huge (6000)' },
        ],
        defaultValue: '4000',
        description: 'Map size in meters (requires wipe)',
      },
      {
        id: 'seed',
        label: 'World Seed',
        type: 'number',
        category: 'World',
        defaultValue: 0,
        description: 'Map generation seed (0 = random)',
      },
      {
        id: 'decay-scale',
        label: 'Decay Scale',
        type: 'slider',
        category: 'Gameplay',
        min: 0,
        max: 2,
        step: 0.1,
        defaultValue: 1.0,
        description: 'Building decay rate multiplier',
      },
    ],
  },

  'ARK Survival Evolved': {
    supportsBasicSettings: true,
    supportsGameMode: false,
    supportsDifficulty: true,
    supportsMaxPlayers: true,
    supportsPassword: true,
    supportsPort: true,
    portEditable: true,
    supportsPublicToggle: true,
    supportsModAutomation: true,
    modType: 'workshop',
    supportsAdvancedConfig: true,
    configFiles: ['Game.ini', 'GameUserSettings.ini'],
    requiresRestartFor: ['difficulty', 'mods', 'xp-multiplier'],
    gameSpecificSettings: [
      {
        id: 'difficulty',
        label: 'Difficulty',
        type: 'slider',
        category: 'Gameplay',
        min: 0,
        max: 10,
        step: 0.5,
        defaultValue: 4,
        description: 'Server difficulty (0-10)',
      },
      {
        id: 'xp-multiplier',
        label: 'XP Multiplier',
        type: 'slider',
        category: 'Gameplay',
        min: 0.1,
        max: 10,
        step: 0.1,
        defaultValue: 1.0,
        description: 'Experience gain multiplier',
      },
      {
        id: 'taming-speed',
        label: 'Taming Speed',
        type: 'slider',
        category: 'Gameplay',
        min: 0.1,
        max: 10,
        step: 0.1,
        defaultValue: 1.0,
        description: 'Dinosaur taming speed multiplier',
      },
      {
        id: 'harvest-multiplier',
        label: 'Harvest Multiplier',
        type: 'slider',
        category: 'Gameplay',
        min: 0.1,
        max: 10,
        step: 0.1,
        defaultValue: 1.0,
        description: 'Resource gathering multiplier',
      },
    ],
  },

  '7 Days to Die': {
    supportsBasicSettings: true,
    supportsGameMode: false,
    supportsDifficulty: false,
    supportsMaxPlayers: true,
    supportsPassword: true,
    supportsPort: true,
    portEditable: true,
    supportsPublicToggle: true,
    supportsModAutomation: false,
    modType: 'manual',
    supportsAdvancedConfig: true,
    configFiles: ['serverconfig.xml'],
    requiresRestartFor: ['all'],
    gameSpecificSettings: [
      {
        id: 'blood-moon-frequency',
        label: 'Blood Moon Frequency',
        type: 'number',
        category: 'Gameplay',
        min: 0,
        max: 30,
        defaultValue: 7,
        description: 'Days between blood moon hordes',
      },
      {
        id: 'loot-abundance',
        label: 'Loot Abundance',
        type: 'slider',
        category: 'Gameplay',
        min: 25,
        max: 400,
        step: 25,
        defaultValue: 100,
        description: 'Loot spawn percentage',
      },
      {
        id: 'xp-multiplier',
        label: 'XP Multiplier',
        type: 'slider',
        category: 'Gameplay',
        min: 50,
        max: 500,
        step: 25,
        defaultValue: 100,
        description: 'Experience gain percentage',
      },
    ],
  },

  "Garry's Mod": {
    supportsBasicSettings: true,
    supportsGameMode: true,
    supportsDifficulty: false,
    supportsMaxPlayers: true,
    supportsPassword: true,
    supportsPort: true,
    portEditable: true,
    supportsPublicToggle: true,
    supportsModAutomation: true,
    modType: 'workshop',
    supportsAdvancedConfig: true,
    configFiles: ['server.cfg'],
    requiresRestartFor: ['gamemode', 'maxplayers', 'map'],
    gameSpecificSettings: [
      {
        id: 'gamemode',
        label: 'Gamemode',
        type: 'select',
        category: 'Gameplay',
        options: [
          { value: 'sandbox', label: 'Sandbox' },
          { value: 'darkrp', label: 'DarkRP' },
          { value: 'ttt', label: 'Trouble in Terrorist Town' },
          { value: 'prop_hunt', label: 'Prop Hunt' },
          { value: 'murder', label: 'Murder' },
        ],
        defaultValue: 'sandbox',
        description: 'Server gamemode',
      },
      {
        id: 'default-map',
        label: 'Default Map',
        type: 'select',
        category: 'Maps',
        options: [
          { value: 'gm_construct', label: 'Construct' },
          { value: 'gm_flatgrass', label: 'Flatgrass' },
          { value: 'gm_bigcity', label: 'Big City' },
        ],
        defaultValue: 'gm_construct',
        description: 'Starting map',
      },
      {
        id: 'pvp-enabled',
        label: 'PvP Enabled',
        type: 'toggle',
        category: 'Gameplay',
        defaultValue: true,
        description: 'Allow player damage',
      },
    ],
  },

  Terraria: {
    supportsBasicSettings: true,
    supportsGameMode: false,
    supportsDifficulty: true,
    supportsMaxPlayers: true,
    supportsPassword: true,
    supportsPort: true,
    portEditable: true,
    supportsPublicToggle: false,
    supportsModAutomation: true,
    modType: 'manual',
    supportsAdvancedConfig: true,
    configFiles: ['serverconfig.txt'],
    requiresRestartFor: ['mods', 'world', 'difficulty'],
    gameSpecificSettings: [
      {
        id: 'world-size',
        label: 'World Size',
        type: 'select',
        category: 'World',
        options: [
          { value: '1', label: 'Small' },
          { value: '2', label: 'Medium' },
          { value: '3', label: 'Large' },
        ],
        defaultValue: '2',
        description: 'World generation size',
      },
      {
        id: 'difficulty',
        label: 'Difficulty',
        type: 'select',
        category: 'Gameplay',
        options: [
          { value: '0', label: 'Normal' },
          { value: '1', label: 'Expert' },
          { value: '2', label: 'Master' },
          { value: '3', label: 'Journey' },
        ],
        defaultValue: '0',
        description: 'Game difficulty mode',
      },
    ],
  },

  Factorio: {
    supportsBasicSettings: true,
    supportsGameMode: false,
    supportsDifficulty: false,
    supportsMaxPlayers: true,
    supportsPassword: true,
    supportsPort: true,
    portEditable: true,
    supportsPublicToggle: true,
    supportsModAutomation: true,
    modType: 'manual',
    supportsAdvancedConfig: true,
    configFiles: ['server-settings.json'],
    requiresRestartFor: ['all'],
    gameSpecificSettings: [
      {
        id: 'autosave-interval',
        label: 'Autosave Interval (minutes)',
        type: 'number',
        category: 'Performance',
        min: 1,
        max: 60,
        defaultValue: 5,
        description: 'Time between automatic saves',
      },
      {
        id: 'afk-auto-kick',
        label: 'AFK Auto-Kick (minutes)',
        type: 'number',
        category: 'Gameplay',
        min: 0,
        max: 120,
        defaultValue: 0,
        description: 'Kick inactive players (0 = disabled)',
      },
      {
        id: 'only-admins-pause',
        label: 'Only Admins Can Pause',
        type: 'toggle',
        category: 'Gameplay',
        defaultValue: true,
        description: 'Restrict pause to administrators',
      },
      {
        id: 'autosave-only-on-server',
        label: 'Server-Side Autosave Only',
        type: 'toggle',
        category: 'Performance',
        defaultValue: true,
        description: 'Only save on server (not clients)',
      },
    ],
  },
};

export function getGameCapabilities(gameName: string): GameCapabilities {
  return (
    GAME_CAPABILITIES[gameName] || {
      supportsBasicSettings: true,
      supportsGameMode: false,
      supportsDifficulty: false,
      supportsMaxPlayers: true,
      supportsPassword: false,
      supportsPort: true,
      portEditable: false,
      supportsPublicToggle: false,
      supportsModAutomation: false,
      modType: 'none',
      supportsAdvancedConfig: false,
      configFiles: [],
      gameSpecificSettings: [],
      requiresRestartFor: ['all'],
    }
  );
}
